import { Link } from "react-router-dom";
import "../position.css";

function Fixed1() {
  return (  
    <div className="body__fondo">
      <div className="siguiente__parte">
        <Link to={"../css/position/position absolute/z-index/position-fixed"}>volver</Link>
      </div>
      <div className="menu__fixed1">
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
      </div>
      <div className="pagina">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.                
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.                
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.                
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
        </p>
      </div>
    </div>
  );
}

export default Fixed1;